name: iOS Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release
  push:
    branches: [ main ]
    paths:
    - 'app/**'
    - 'package.json'
    - 'nativescript.config.ts'

env:
  NODE_VERSION: '18'

jobs:
  ios-build:
    name: Build iOS App
    runs-on: macos-latest
    if: github.repository_owner == 'tmctyres' # Only run on main repository
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Remove compiled JS files
      run: find app -name "*.js" -not -path "*/node_modules/*" -delete || true
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install NativeScript CLI
      run: npm install -g @nativescript/cli
      
    - name: Add iOS platform
      run: ns platform add ios
      
    - name: Prepare iOS
      run: ns prepare ios
      
    - name: Build iOS Debug
      if: ${{ github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == '' }}
      run: ns build ios --for-device
      
    - name: Build iOS Release
      if: ${{ github.event.inputs.build_type == 'release' }}
      run: ns build ios --for-device --release
      
    - name: Archive iOS build
      uses: actions/upload-artifact@v3
      with:
        name: ios-build-${{ github.event.inputs.build_type || 'debug' }}
        path: |
          platforms/ios/build/
          platforms/ios/*.xcworkspace
          
    - name: Create IPA (if release)
      if: ${{ github.event.inputs.build_type == 'release' }}
      run: |
        # This would require proper code signing certificates
        echo "IPA creation requires code signing certificates"
        echo "Configure certificates in repository secrets for automated IPA creation"
        
    - name: Build Summary
      run: |
        echo "✅ iOS build completed successfully!"
        echo "📱 Build type: ${{ github.event.inputs.build_type || 'debug' }}"
        echo "📦 Build artifacts available for download"
        echo "🔧 For release builds, configure code signing certificates"
